config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'user/show'
  get 'static_pages/landing_page'
  get 'static_pages/dashboard'
  get 'static_pages/valid_airdrip', to: 'static_pages#valid_airdrip', as: 'valid_airdrip'


  resources :albums, param: :report_id do
    post 'validate', on: :member
    #get 'index', on: :collection
    get 'dashboard', on: :member

  end

    #root 'gib#index' # Add this line to set the root page to the index action of the Gib controller 
    resources :gib, param: :report_id do
      post 'validate', on: :member
      #get 'index', on: :collection
      get 'dashboard', on: :member
    end


  

   #namespace :albums do
   #  resources :songs
   #end
   
 resources :songs, only: [:index], path: 'my-mining-report'
 resources :networks, only: [:index], path: 'network-activity'
 resources :scoreboards, only: [:index], path: 'my-airdrips'


 resources :tag, only: [:index]


  # Versuch MY an Songs/my, custom action in songs controller
  get '/my', to: "songs#my"

  resources :songs do
    collection do
      get 'my'
    end
  end
  # ENDE Versuch MY an Songs/my

   #  get '/songs/report/:report_id', to: 'songs#index', as: 'songs_report'
   #  get 'songs/:report_id', to: 'songs#show'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show], param: :slug

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: "home#index"
  root 'static_pages#landing_page'

  post 'albums/validate_code', to: 'albums#validate_code'
  post 'gib/validate_code', to: 'gib#validate_code'

  get 'dashboard', to: 'albums#index'


end

app/controllers/gib_controller.rb
class GibController < ApplicationController

    def aktion
        @data = [1, 2, 3, 4, 5]
    end

    def index
      redirect_to root_path
    end

    def show
  
  
      #  @album = Album.find_by(id: params[:report_id])
        #@songs = Song.where(report_id: @album.report_id)
  
       # @songs = @album.songs
        @album = Album.find_by(report_id: params[:report_id])
      #    @album = Album.find(report_id: params[:report_id])
        #@songs = Song.where(report_id: @album.report_id)
    end
     
    def validate
        @album = Album.find(params[:id])
        if @album.validate_code(params[:code], current_user.id)
          flash[:notice] = "Validation code successfully applied."
        else
          flash[:alert] = "Invalid validation code."
        end
        redirect_to @album
    end
  





end

app/helpers/gib_helper.rb
module GibHelper
end

app/views/gib/aktion.html.erb
<h1>Custom Action</h1>
<ul>
  <% @data.each do |item| %>
    <li><%= item %></li>
  <% end %>
</ul>

app/views/gib/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Four Apes", root_path, class: "navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">


    <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to "Mining report", songs_path, class: "nav-link" %>
    </li>
  </ul>
  
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Airdrips", scoreboards_path, class: "nav-link" %>
        </li>
      </ul>
  
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Network activity", networks_path, class: "nav-link" %>
        </li>
      </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %> 
        </li>

        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  <% end %>
</nav>



<br></br>


<h1>Registration of an Airdrip</h1>

<p><strong>Name:</strong> <%= @album.report_name %></p>

<p><strong>Latitude:</strong> <%= @album.latitude %></p>
<p><strong>Longitude:</strong> <%= @album.longitude %></p>

<% if !@album.gebraucht %>
  <%= form_tag validate_album_url(@album), method: :post do %>
    <%= text_field_tag :code %>
    <%= submit_tag "Validate" %>
  <% end %>
<% end %>